### ISSUE TITLE
Fix ncbo_ontology_process script to avoid print Annotator dictionary in the logs

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/ncbo_cron#6]
At the end of the script, the ncbo_ontology_process script print in the console the content of the Annotator cache. 
We should fix this as it prevents reading the script when run in the console.

**Comment by jonquet** [comment]
Might be related : https://github.com/ncbo/ncbo_annotator/issues/16

**Comment by syphax-bouazzouni** [comment]
fixed https://github.com/ontoportal-lirmm/ncbo_annotator/commit/2ebcb237008958d7a8eb45319cd986312a814dae
